1. Create a 1-dimensional NumPy array arr containing 12 random integers between 100 and 1000 (inclusive). Reshape arr into a 3D matrix matrix of shape (2, 2, 3) using reshape. Replace all even numbers in matrix with 0. Finally, calculate the sum of all the elements in matrix and print the result.

In [30]:
import numpy as np

arr = np.random.randint(100, 1001, 12)
print (f"\nOriginal matrix:\n {arr}\n")

matrix = arr.reshape((2, 2, 3))
print(f"reshape matrix:\n {matrix}\n")

matrix[matrix % 2 == 0] = 0
print(f"replace matrix:\n {matrix}")

matrix_sum = np.sum(matrix)
print("\nSum of all elements in the matrix:", matrix_sum)


Original matrix:
 [537 836 624 714 247 599 440 588 924 515 463 157]

reshape matrix:
 [[[537 836 624]
  [714 247 599]]

 [[440 588 924]
  [515 463 157]]]

replace matrix:
 [[[537   0   0]
  [  0 247 599]]

 [[  0   0   0]
  [515 463 157]]]

Sum of all elements in the matrix: 2518


2.Create a 2-dimensional NumPy array, arr, of shape (4, 5), filled with random integers between 1 and 100 (inclusive). Reshape the array into a 1-dimensional array of shape (20,). Replace all the even numbers in the reshaped array with 0 and print the resulting array.

In [35]:
import numpy as np

arr = np.random.randint(1, 101, (4, 5))
print (f"\nOriginal matrix:\n {arr}\n")

arr_reshaped = arr.reshape(20)
print(f"reshape matrix:\n {arr_reshaped}\n")

arr_reshaped[arr_reshaped % 2 == 0] = 0
print(f"reshape matrix even:\n {arr_reshaped}\n")


Original matrix:
 [[19 56 18 21  2]
 [48 92 82 92 55]
 [44 53 78 95 41]
 [68 21 31 65 51]]

reshape matrix:
 [19 56 18 21  2 48 92 82 92 55 44 53 78 95 41 68 21 31 65 51]

reshape matrix even:
 [19  0  0 21  0  0  0  0  0 55  0 53  0 95 41  0 21 31 65 51]



3. Write a Python program that uses the numpy library to create a 1-dimensional array containing 100 equally spaced values between 0 and 10 (inclusive) . Reshape the array into a 10x10 matrix and calculate the sum of each row. Print the resulting array containing the sums.

In [2]:
import numpy as np
arr = np.linspace(0,10,100)
#arr = np.arange(0, 10, 0.1)
print (f"\nOriginal matrix:\n {arr}\n")

matrix = arr.reshape((10, 10))
print(f"reshape matrix:\n {matrix}\n")

row_sums = np.sum(matrix, axis=1)
print(f"matrix row sum:\n {row_sums}\n")


Original matrix:
 [ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.0808

4. You have a 1-dimensional NumPy array, arr, containing 100 elements of random integers between 1 and 1000 (inclusive). Reshape the array into a 10x10 matrix. Find the average value of each row and column separately, and store the results in two separate 1-dimensional arrays. Print the resulting arrays.

In [2]:
import numpy as np

arr = np.random.randint(1, 1001, 100)
print (f"\nOriginal matrix:\n {arr}\n")

matrix = arr.reshape((10, 10))
print(f"reshape matrix:\n {matrix}\n")

row_averages = np.mean(matrix, axis=1)
print(f"matrix row average:\n {row_averages}\n")

column_averages = np.mean(matrix, axis=0)
print(f"matrix column average:\n {column_averages}\n")


Original matrix:
 [254  53 523 271 579 333 881 401 342 617 323 581 154 446  48  90 479 938
 229 156 557 341 277 298  67 908 890 843 326 524 184 786 557 775 443  56
 409 136 724  20 285 131 563 496 746 988 885 963 494 911   8 324 605 636
 375 332 653 694 716 835  45 421 309 444 117 456 202 804 827 238  93 794
 865 903 886 566 969 117 982 556 612 514 468 396 323 329 994 621 916 341
 957  22 885 278 739  76 160 731 670  61]

reshape matrix:
 [[254  53 523 271 579 333 881 401 342 617]
 [323 581 154 446  48  90 479 938 229 156]
 [557 341 277 298  67 908 890 843 326 524]
 [184 786 557 775 443  56 409 136 724  20]
 [285 131 563 496 746 988 885 963 494 911]
 [  8 324 605 636 375 332 653 694 716 835]
 [ 45 421 309 444 117 456 202 804 827 238]
 [ 93 794 865 903 886 566 969 117 982 556]
 [612 514 468 396 323 329 994 621 916 341]
 [957  22 885 278 739  76 160 731 670  61]]

matrix row average:
 [425.4 344.4 503.1 409.  646.2 517.8 386.3 673.1 551.4 457.9]

matrix column average:
 [331.8 396.7 520

5. You have a 1-dimensional NumPy array arr of size 20, filled with random floating-point numbers between 0 and 1 (inclusive). Reshape arr into a 4x5 matrix. Replace all values in the matrix that are less than 0.5 with 0. Calculate the sum of each column in the modified matrix and print the resulting array.

In [3]:
import numpy as np

arr = np.random.rand(20)
print (f"\nOriginal matrix:\n {arr}\n")

matrix = arr.reshape((4, 5))
print(f"reshape matrix:\n {matrix}\n")

matrix[matrix < 0.5] = 0
print(f"reshape matrix con:\n {matrix}\n")

column_sums = np.sum(matrix, axis=0)
print(f"matrix column sum:\n {column_sums}\n")


Original matrix:
 [0.16718831 0.61004208 0.712985   0.51187613 0.80080876 0.95329469
 0.95652231 0.21101033 0.78602835 0.81082678 0.81961753 0.53925378
 0.81123516 0.4641944  0.27874446 0.09350346 0.96988014 0.58436445
 0.8895235  0.38049321]

reshape matrix:
 [[0.16718831 0.61004208 0.712985   0.51187613 0.80080876]
 [0.95329469 0.95652231 0.21101033 0.78602835 0.81082678]
 [0.81961753 0.53925378 0.81123516 0.4641944  0.27874446]
 [0.09350346 0.96988014 0.58436445 0.8895235  0.38049321]]

reshape matrix con:
 [[0.         0.61004208 0.712985   0.51187613 0.80080876]
 [0.95329469 0.95652231 0.         0.78602835 0.81082678]
 [0.81961753 0.53925378 0.81123516 0.         0.        ]
 [0.         0.96988014 0.58436445 0.8895235  0.        ]]

matrix column sum:
 [1.77291222 3.07569832 2.10858461 2.18742798 1.61163554]

